2025-05-22 05:49:26 UTC
Windows-10-10.0.26100
Ren'Py 8.3.7.25031702

Early init took 0.10s
Loading error handling took 0.05s
Loading script took 0.20s
Loading save slot metadata took 0.05s
Loading persistent took 0.00s
Running init code took 0.07s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.04s
Index archives took 0.00s
Dump and make backups took 0.07s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.10s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 0.01s
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.01s
Load screen analysis took 0.04s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.10s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Interface start took 0.47s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'ATI Technologies Inc.'"
Renderer: b'AMD Radeon(TM) Graphics'
Version: b'4.6.0 Compatibility Profile Context 22.20.44.45.230320'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1724, 970) drawable=(1724, 970)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 72, in script
    pause(1.0)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 1367, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 72, in <module>
    pause(1.0)
NameError: name 'xzoom' is not defined

While running game code:
  File "game/script.rpy", line 72, in script
    pause(1.0)
  File "game/script.rpy", line 72, in <module>
    pause(1.0)
NameError: name 'xzoom' is not defined
Resetting cache.
Early init took 322.62s
Loading error handling took 0.04s
Loading script took 0.31s
Loading save slot metadata took 0.03s
Loading persistent took 0.00s
Running init code took 0.04s
Loading analysis data took 0.02s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.03s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\Hina\\AppData\\Roaming/RenPy/backups\\MentalHealthVN':
Dump and make backups took 0.08s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.11s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.02s
Save screen analysis took 0.03s
Prepare screens took 0.11s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Interface start took 0.42s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'ATI Technologies Inc.'"
Renderer: b'AMD Radeon(TM) Graphics'
Version: b'4.6.0 Compatibility Profile Context 22.20.44.45.230320'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1724, 970) drawable=(1724, 970)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 74, in script
    show haru sad talk
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'haru sad' does not accept attributes 'talk'.

While running game code:
  File "game/script.rpy", line 74, in script
    show haru sad talk
Exception: Image 'haru sad' does not accept attributes 'talk'.
